spring:
  application:
    name: api-gateway
  config:
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 3
            statuses: SERVICE_UNAVAILABLE,BAD_GATEWAY
            methods: GET,POST,PUT,DELETE
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
      routes:
        - id: vets-service
          uri: http://vets-service:8083
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://visits-service:8082
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://customers-service:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: http://genai-service:8084
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      reactor.netty.http.client: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
