# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: api-gateway
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['api-gateway:8080']

- job_name: customers-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['customers-service:8081']

- job_name: visits-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['visits-service:8082']

- job_name: vets-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['vets-service:8083']

# Istio config metrics
- job_name: istio-envoy
  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  # Keep only pods with istio sidecar
  - source_labels: [__meta_kubernetes_pod_container_name]
    action: keep
    regex: istio-proxy

  # Use envoy metrics port
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: (.+)
    replacement: $1

  # Fallback to default envoy port
  - source_labels: [__address__]
    action: replace
    target_label: __address__
    regex: (.+)
    replacement: ${1}:15090

  metrics_path: /stats/prometheus

